// prettier-ignore
export const registry = [
      //transaction entities
  { handle: 'Bill',             name: 'Bill',             fragment: 'bill',           query:true,  create:true,  read: true,  update: true,  delete: true },
  { handle: 'BillPayment',      name: 'BillPayment',      fragment: 'billpayment',    query:true,  create:true,  read: true,  update: true,  delete: true },
  { handle: 'CreditMemo',       name: 'CreditMemo',       fragment: 'creditmemo',     query:true,  create:true,  read: true,  update: true,  delete: true },
  { handle: 'Deposit',          name: 'Deposit',          fragment: 'deposit',        query:true,  create:true,  read: true,  update: true,  delete: true },
  { handle: 'Estimate',         name: 'Estimate',         fragment: 'estimate',       query:true,  create:true,  read: true,  update: true,  delete: true },
  { handle: 'Invoice',          name: 'Invoice',          fragment: 'invoice',        query:true,  create:true,  read: true,  update: true,  delete: true },
  { handle: 'JournalEntry',     name: 'JournalEntry',     fragment: 'journalentry',   query:true,  create:true,  read: true,  update: true,  delete: true },
  { handle: 'Payment',          name: 'Payment',          fragment: 'payment',        query:true,  create:true,  read: true,  update: true,  delete: true },
  { handle: 'Purchase',         name: 'Purchase',         fragment: 'purchase',       query:true,  create:true,  read: true,  update: true,  delete: true },
  { handle: 'Purchaseorder',    name: 'Purchaseorder',    fragment: 'purchaseorder',  query:true,  create:true,  read: true,  update: true,  delete: true },
  { handle: 'RefundReceipt',    name: 'RefundReceipt',    fragment: 'refundreceipt',  query:true,  create:true,  read: true,  update: true,  delete: true },
  { handle: 'SalesReceipt',     name: 'SalesReceipt',     fragment: 'salesreceipt',   query:true,  create:true,  read: true,  update: true,  delete: true },
  { handle: 'TimeActivity',     name: 'TimeActivity',     fragment: 'timeactivity',   query:true,  create:true,  read: true,  update: true,  delete: true },
  { handle: 'Transfer',         name: 'Transfer',         fragment: 'transfer',       query:true,  create:true,  read: true,  update: true,  delete: true },
  { handle: 'VendorCredit',     name: 'VendorCredit',     fragment: 'vendorcredit',   query:true,  create:true,  read: true,  update: true,  delete: true },
  //named list entities
  { handle: 'Account',            name: 'Account',          fragment: 'account',           query: true,  create:true,  read: true,  update: true,  delete: false },
  { handle: 'Budget',             name: 'Budget',           fragment: 'budget',            query: true,  create:false, read: true,  update: false, delete: false },
  { handle: 'Class',              name: 'Class',            fragment: 'class',             query: true,  create:true,  read: true,  update: true,  delete: false },
  { handle: 'CompanyCurrency',    name: 'CompanyCurrency',  fragment: 'companycurrency',   query: true,  create:true,  read: true,  update: true,  delete: true },
  { handle: 'Customer',           name: 'Customer',         fragment: 'customer',          query: true,  create:true,  read: true,  update: true,  delete: false },
  { handle: 'Department',         name: 'Department',       fragment: 'department',        query: true,  create:true,  read: true,  update: true,  delete: false },
  { handle: 'Employee',           name: 'Employee',         fragment: 'employee',          query: true,  create:true,  read: true,  update: true,  delete: false },
  { handle: 'Item',               name: 'Item',             fragment: 'item',              query: true,  create:true,  read: true,  update: true,  delete: false },
  { handle: 'Journalcode',        name: 'Journalcode',      fragment: 'journalcode',       query: true,  create:true,  read: true,  update: true,  delete: false },//FR only.
  { handle: 'PaymentMethod',      name: 'PaymentMethod',    fragment: 'paymentmethod',     query: true,  create:true,  read: true,  update: true,  delete: false },
  { handle: 'TaxAgency',          name: 'TaxAgency',        fragment: 'taxagency',         query: true,  create:true,  read: true,  update: false, delete: false },
  { handle: 'TaxCode',            name: 'TaxCode',          fragment: 'taxcode',           query: true,  create:false, read: true,  update: false, delete: false },
  { handle: 'TaxRate',            name: 'TaxRate',          fragment: 'taxrate',           query: true,  create:true,  read: true,  update: false, delete: false },
  { handle: 'TaxService',         name: 'TaxService',       fragment: 'taxservice/taxcode',query: false, create:true,  read: false, update: false, delete: false },
  { handle: 'Term',               name: 'Term',             fragment: 'term',              query: true,  create:true,  read: true,  update: true,  delete: false },
  { handle: 'Vendor',             name: 'Vendor',           fragment: 'vendor',            query: true,  create:true,  read: true,  update: true,  delete: false },
  //supporting entities
  { handle: 'Attachable',         name: 'Attachable',       fragment: 'attachable',        query: true,  create:true,  read: true,  update: true,  delete: true },
  { handle: 'CompanyInfo',        name: 'CompanyInfo',      fragment: 'companyinfo',       query: true,  create:false, read: true,  update: true,  delete: false },
  { handle: 'ExchangeRate',       name: 'ExchangeRate',     fragment: 'exchangerate',      query: true,  create:false, read: false, update: true,  delete: false },
  { handle: 'Preferences',        name: 'Preferences',      fragment: 'preferences',       query: true,  create:false, read: true,  update: true,  delete: false },
  //reports
  { handle: 'AccountListDetailReport',          name: 'AccountList',                  fragment: 'AccountList',                report: true },
  { handle: 'APAgingDetailReport',              name: 'AgedPayableDetail',            fragment: 'AgedPayableDetail',          report: true },
  { handle: 'APAgingSummaryReport',             name: 'AgedPayables',                 fragment: 'AgedPayables',               report: true },
  { handle: 'ARAgingDetailReport',              name: 'AgedReceivableDetail',         fragment: 'AgedReceivableDetail',       report: true },
  { handle: 'ARAgingSummaryReport',             name: 'AgedReceivables',              fragment: 'AgedReceivables',            report: true },
  { handle: 'BalanceSheetReport',               name: 'BalanceSheet',                 fragment: 'BalanceSheet',               report: true },
  { handle: 'CashFlowReport',                   name: 'CashFlow',                     fragment: 'CashFlow',                   report: true },
  { handle: 'CustomerBalanceReport',            name: 'CustomerBalance',              fragment: 'CustomerBalance',            report: true },
  { handle: 'CustomerBalanceDetailReport',      name: 'CustomerBalanceDetail',        fragment: 'CustomerBalanceDetail',      report: true },
  { handle: 'CustomerIncomeReport',             name: 'CustomerIncome',               fragment: 'CustomerIncome',             report: true },
  { handle: 'GeneralLedgerReport',              name: 'GeneralLedger',                fragment: 'GeneralLedger',              report: true },
  { handle: 'GeneralLedgerReportFR',            name: 'GeneralLedgerFR',              fragment: 'GeneralLedgerFR',            report: true }, //FR locale
  { handle: 'InventoryValuationSummaryReport',  name: 'InventoryValuationSummary',    fragment: 'InventoryValuationSummary',  report: true },
  { handle: 'JournalReport',                    name: 'JournalReport',                fragment: 'JournalReport',              report: true },
  { handle: 'ProfitAndLossReport',              name: 'ProfitAndLoss',                fragment: 'ProfitAndLoss',              report: true },
  { handle: 'ProfitAndLossDetailReport',        name: 'ProfitAndLossDetail',          fragment: 'ProfitAndLossDetail',        report: true },
  { handle: 'SalesByClassSummaryReport',        name: 'ClassSales',                   fragment: 'ClassSales',                 report: true },
  { handle: 'SalesByCustomerReport',            name: 'CustomerSales',                fragment: 'CustomerSales',              report: true },
  { handle: 'SalesByDepartmentReport',          name: 'DepartmentSales',              fragment: 'DepartmentSales',            report: true },
  { handle: 'SalesByProductReport',             name: 'ItemSales',                    fragment: 'ItemSales',                  report: true },
  { handle: 'TaxSummaryReport',                 name: 'TaxSummary',                   fragment: 'TaxSummary',                 report: true },
  { handle: 'TransactionListReport',            name: 'TransactionList',              fragment: 'TransactionList',            report: true },
  { handle: 'TransactionListWithSplitsReport',  name: 'TransactionListWithSplits',    fragment: 'TransactionListWithSplits',  report: true },
  { handle: 'TrialBalanceReportFR',             name: 'TrialBalanceFR',               fragment: 'TrialBalanceFR',             report: true }, //FR locale
  { handle: 'TrialBalanceReport',               name: 'TrialBalance',                 fragment: 'TrialBalance',               report: true },
  { handle: 'VendorBalanceReport',              name: 'VendorBalance',                fragment: 'VendorBalance',              report: true },
  { handle: 'VendorBalanceDetailReport',        name: 'VendorBalanceDetail',          fragment: 'VendorBalanceDetail',        report: true },
  { handle: 'VendorExpensesReport',             name: 'VendorExpenses',               fragment: 'VendorExpenses',             report: true },
 ] as const;
